tests=: <;._2 [ 0 : 0
test/admin_test.ijs
test/alloc_test.ijs
test/basic_test.ijs
test/byten_test.ijs
test/cd_query_test.ijs
test/createcol_derived_test.ijs
test/createcol_test.ijs
test/createtable_test.ijs
test/csv_test.ijs
test/csvcdefs_test.ijs
test/csvrd_types_test.ijs
test/delete_test.ijs
test/drop_rename_test.ijs
test/droptable_test.ijs
test/epoch_test.ijs
test/error_test.ijs
test/fixpairs_test.ijs
test/info_test.ijs
test/insert_revert_test.ijs
test/insert_test.ijs
test/intx_test.ijs
test/jdindex_test.ijs
test/jds_test.ijs
test/join_test.ijs
test/join_type_test.ijs
test/joinorder_test.ijs
test/joinx_test.ijs
test/keyindex_test.ijs
test/log_test.ijs
test/modify_test.ijs
test/multicol_test.ijs
test/names_test.ijs
test/northwind_test.ijs
test/orderby_test.ijs
test/osfna_test.ijs
test/pm_aggby_test.ijs
test/ptable_csv_test.ijs
test/ptable_delete_test.ijs
test/ptable_insert_test.ijs
test/ptable_modify_test.ijs
test/ptable_read_test.ijs
test/ptable_update_test.ijs
test/query_test.ijs
test/read_types_test.ijs
test/readx_test.ijs
test/ref_dirty_test.ijs
test/ref_test.ijs
test/refx_test.ijs
test/repair_test.ijs
test/replicate_test.ijs
test/rmdir_test.ijs
test/sandp_test.ijs
test/sed_test.ijs
test/shape_test.ijs
test/sort_test.ijs
test/stress_test.ijs
test/table_append_test.ijs
test/update_test.ijs
test/upsert_test.ijs
test/user_test.ijs
test/utf8_test.ijs
test/valid_data_test.ijs
test/validate_test.ijs
test/where_test.ijs
)